#!/bin/sh

echo "==========Anthon Open Source Community=========="
echo ""
echo "[1] Simplified Chinese"
echo "[2] English"
echo "Choose a language:"
read cho





if [ "$cho" == "1" ]
then
echo ""
echo "安同开始程序 for Linux终端 版本 0.0.0.0100"
echo "开始程序暂未支持简体中文操作，抱歉！"
exit
fi





if [ "$cho" == "2" ]
then
echo ""
echo "=====>>>Anthon-Starter for Linux-console version 0.0.0.0100<<<====="
echo "The program needs root."
echo ""
echo "Before we install Anthon GNU/Linux we need some information."
echo -n "1. ISO file of Anthon GNU/Linux:"
read atfile
if [ ! -e $atfile ]
then
	echo "ISO file does not exist! Please try again."
	unset atfile
	echo -n "1. ISO file of Anthon GNU/Linux:"
	read atfile
	if [ ! -e $atfile ]
	then
		echo "ISO file does not exist! Will exit the program."
		unset cho
		unset atfile
		exit
	fi
fi
echo ""
echo -n "2. Position ( Example: /dev/sda1 ):"
read attarget
echo ""

# mkdir /anthonos-iso
# mount -o loop $atfile /anthonos-iso
# if [ ! -e /anthonos-iso/tarball.tar.xz ]
# then
# 	echo "Maybe it's not Anthon GNU/Linux and we can't opetare it."
# 	echo "Will now exit."
# 	umount /anthonos-iso
# 	unset atfile
# 	unset attarget
# 	exit
# fi
# mkdir /anthonos-tgt
# if mount $attarget /anthonos-tgt
# then
# 

echo "Currently we only need these information."
echo "Please wait while installation is running."
echo ""
echo "Prepairing files..."
sleep 2
echo "Extracting files..."
sleep 2
echo "Deploying startup..."
sleep 1
# cp $atfile /anthonos
# cd /anthonos
# tar ...
# update-grub
# OR MORE FOR LILO/SYSLINUX/...?

echo ""
echo "----->>>Anthon GNU/Linux is installed to your computer successfully.<<<-----"
echo ""
echo "Now you can:"
echo "[1] Run chroot to enter Anthon GNU/Linux"
echo "[2] Restart your computer"
echo "[3] Close Anthon-Starter"
echo ""
echo -n "Please choose an option:"
read endcho
# umount /attarget
# and of cource more...
unset atfile
unset attarget
unset cho
unset endcho
fi
